version: '3.9'

services:
  frontend_build:
    build:
      context: frontend
      dockerfile: build.Dockerfile
    volumes:
      - frontend_dist:/build/dist
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: backend/.env
    depends_on:
      db:
        condition: service_healthy
  load_balancer:
    build:
      context: lb
    depends_on:
      frontend_build:
        condition: service_completed_successfully
      backend:
        condition: service_started
      # backend:
      #   condition: service_completed_successfully
    volumes:
      - frontend_dist:/var/www/html
    ports:
      - 8080:80
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pong
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_prod
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s

volumes:
  frontend_dist:

#   frontend:
#     container_name: frontend
#     build:
#       context: frontend/
#     ports:
#       - 8080:8080
#     networks:
#       - pong
#   backend:
#     container_name: backend
#     hostname: backend
#     build:
#       context: backend/
#     depends_on:
#       - db
#     env_file: backend/.env
#     networks:
#       - pong
#   db:
#     container_name: db
#     hostname: db
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=pong
#       - POSTGRES_PASSWORD=123
#       - POSTGRES_DB=nest-db
#     restart: unless-stopped
#     networks:
#       - pong

# networks:
#   pong:
