version: '3.9'

services:
  frontend_build:
    build:
      context: frontend
      dockerfile: build.Dockerfile
    volumes:
      - frontend_dist:/build/dist
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: backend/.env.prod
    depends_on:
      db:
        condition: service_healthy
  load_balancer:
    build:
      context: lb
    depends_on:
      frontend_build:
        condition: service_completed_successfully
      backend:
        condition: service_started
    volumes:
      - frontend_dist:/var/www/html
    ports:
      - 8080:80
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pong
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_prod
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s

volumes:
  frontend_dist:
