version: '3.9'

services:

    dev-db:
      image: postgres:latest
      ports:
        - 5434:5432
      environment:
        - POSTGRES_USER=pong
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=nest-db
      restart: unless-stopped
      networks:
        - pong

networks:
  pong:
